services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $filesStorage: '@contao.filesystem.virtual.files'
            $validExtensions: '%contao.image.valid_extensions%'

    Markocupic\ContaoThemeCaribbeanBlue\:
        resource: ../src/
        exclude: ../src/{DependencyInjection}
